#firbase secret key
fcm.secret.key=
# ======================
# SendGrid configuration
# ======================
sendgrid.api.key=REDACTED
mail.from.email=salamioluwasegun.a@gmail.com
mail.from.name=APMIS Support
app.base.url=https://afghanistan-apmis.com