#firbase secret key
 
fcm.secret.key=
# ======================
# SendGrid configuration
# ======================
sendgrid.api.key=${SENDGRID_API_KEY}
mail.from.email=${MAIL_FROM_EMAIL:passwordreset@afghanistan-apmis.com}
mail.from.name=${MAIL_FROM_NAME:APMIS Support}
app.base.url=${APP_BASE_URL:https://afghanistan-apmis.com}
 