---
# Test the Android app with Gradle and an emulator.

name: Java CI with Gradle

env:
  JAVA: "17"
  PRIVILEGED_RUN: >-
    ${{ (github.event_name == 'push' &&
    github.ref == 'refs/heads/development') ||
    github.event.pull_request.head.repo.full_name == github.repository }}

on:
  workflow_dispatch:
  push:
    branches: [development, master]
    paths:
      - "sormas-app/**"
      - "sormas-api/**"
  pull_request:
    branches: [development]
    paths:
      - "sormas-app/**"
      - "sormas-api/**"

permissions:
  contents: read

concurrency:
  group: apmis-app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: APMIS app build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        api-level: [28]

    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' |
            sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout repository (with token)
        if: ${{ fromJSON(env.PRIVILEGED_RUN) }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAVEN_ACTIONS_TOKEN }}

      - name: Checkout repository (without token)
        if: ${{ !fromJSON(env.PRIVILEGED_RUN) }}
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA }}
          distribution: zulu

      - name: Cache Maven packages
        if: ${{ fromJSON(env.PRIVILEGED_RUN) }}
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: >-
            ${{ runner.os }}-java-${{ env.JAVA }}-m2-
            ${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-java-${{ env.JAVA }}-m2

      - name: Build sormas-api for app dependencies
        working-directory: ./sormas-base
        run: mvn install -pl :sormas-api -am -DskipTests=true

      - name: Cache Gradle packages
        if: ${{ fromJSON(env.PRIVILEGED_RUN) }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            ${{ runner.os }}-gradle-
            ${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ensure Gradle wrapper is executable
        working-directory: ./sormas-app
        run: chmod +x gradlew

      - name: Run unit tests
        working-directory: ./sormas-app
        run: ./gradlew :app:clean :app:assembleDebug :app:test

      - name: AVD cache
        if: ${{ fromJSON(env.PRIVILEGED_RUN) }}
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-x86_64

      - name: Create AVD snapshot for cache
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          ram-size: 2048M
          heap-size: 512M
          force-avd-creation: false
          emulator-options: >-
            -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
            -camera-back none -memory 2048
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          ram-size: 2048M
          heap-size: 512M
          force-avd-creation: false
          emulator-options: >-
            -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
            -no-boot-anim -camera-back none -memory 2048
          disable-animations: true
          working-directory: ./sormas-app
          script: ./gradlew connectedAndroidTest

      - name: Run mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: ". --sarif --output mobsf-results.sarif || true"

      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: mobsf-results.sarif
          category: code-scanning/mobsfscan